var paydata = [
  {
    "iconName":"icon-canyin",
    "iconMsg":"餐饮"
  },
  {
    "iconName":"icon-gouwu",
    "iconMsg":"购物"
  },
  {
    "iconName":"icon-jiaotong",
    "iconMsg":"交通"
  },
  {
    "iconName":"icon-yule",
    "iconMsg":"娱乐"
  },
  {
    "iconName":"icon-tongxun",
    "iconMsg":"通讯"
  },
  {
    "iconName":"icon-zhufang",
    "iconMsg":"住房"
  },
  {
    "iconName":"icon-xuexi",
    "iconMsg":"学习"
  },
  {
    "iconName":"icon-fushi",
    "iconMsg":"服饰"
  },
  {
    "iconName":"icon-meirong",
    "iconMsg":"美容"
  },
  {
    "iconName":"icon-shuma",
    "iconMsg":"数码"
  },
  {
    "iconName":"icon-shuiguo",
    "iconMsg":"水果"
  },
  {
    "iconName":"icon-lingshi",
    "iconMsg":"零食"
  },
  {
    "iconName":"icon-riyongpin",
    "iconMsg":"日用"
  },
  {
    "iconName":"icon-kuaidihuoyun",
    "iconMsg":"快递"
  },
  {
    "iconName":"icon-changbei",
    "iconMsg":"长辈"
  },
  {
    "iconName":"icon-caipiao",
    "iconMsg":"彩票"
  },
  {
    "iconName":"icon-aixinjuanzeng",
    "iconMsg":"捐赠"
  },
  {
    "iconName":"icon-weixiu",
    "iconMsg":"维修"
  },
  {
    "iconName":"icon-bangong",
    "iconMsg":"办公"
  },
  {
    "iconName":"icon-liwu",
    "iconMsg":"礼物"
  },
  {
    "iconName":"icon-qiche",
    "iconMsg":"汽车"
  },
  {
    "iconName":"icon-yanjiu",
    "iconMsg":"烟酒"
  },
  {
    "iconName":"icon-lvxing",
    "iconMsg":"旅行"
  },
  {
    "iconName":"icon-shejiao",
    "iconMsg":"社交"
  },
  {
    "iconName":"icon-haizi",
    "iconMsg":"孩子"
  },
  {
    "iconName":"icon-jujia",
    "iconMsg":"居家"
  },
  {
    "iconName":"icon-yundong",
    "iconMsg":"运动"
  },
  {
    "iconName":"icon-yiliao",
    "iconMsg":"医疗"
  },
  {
    "iconName":"icon-shuji",
    "iconMsg":"书籍"
  },
  {
    "iconName":"icon-chongwu",
    "iconMsg":"宠物"
  },
  {
    "iconName":"icon-pengyou",
    "iconMsg":"社交"
  },
  {
    "iconName":"icon-huluobushucaiqu",
    "iconMsg":"蔬菜"
  },
  {
    "iconName":"icon-shezhi",
    "iconMsg":"设置"
  },
]

let getdata = [
  {
    "iconName":"icon-gongzi",
    "iconMsg":"工资"
  },
  {
    "iconName":"icon-jianzhi",
    "iconMsg":"兼职"
  },
  {
    "iconName":"icon-licaishouyi",
    "iconMsg":"理财"
  },
  {
    "iconName":"icon-lijin",
    "iconMsg":"礼金"
  },
  {
    "iconName":"icon-qitashouru",
    "iconMsg":"其他"
  },
  {
    "iconName":"icon-shezhi",
    "iconMsg":"设置"
  },
]
module.exports = {
  paydata,
  getdata
}